=== StylishFlash/DatabankenExamenNieuw/XML & XQuery/Week.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 (x64) (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="zondag">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vertoning" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="zetelreservatie">
		<xs:complexType/>
	</xs:element>
	<xs:element name="zaterdag">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vertoning" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="zaalId">
		<xs:complexType/>
	</xs:element>
	<xs:element name="woensdag">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vertoning" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="week">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="maandag"/>
				<xs:element ref="dinsdag"/>
				<xs:element ref="woensdag"/>
				<xs:element ref="donderdag"/>
				<xs:element ref="vrijdag"/>
				<xs:element ref="zaterdag"/>
				<xs:element ref="zondag"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="vrijdag">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vertoning" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="vertoning">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="is3D"/>
				<xs:element ref="taal"/>
				<xs:element ref="tijdstip"/>
				<xs:element ref="zetelreservatie"/>
				<xs:element ref="filmId"/>
				<xs:element ref="zaalId"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tijdstip">
		<xs:complexType>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="date"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="taal">
		<xs:complexType/>
	</xs:element>
	<xs:element name="maandag">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vertoning" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="is3D">
		<xs:complexType/>
	</xs:element>
	<xs:element name="id">
		<xs:complexType/>
	</xs:element>
	<xs:element name="filmId">
		<xs:complexType/>
	</xs:element>
	<xs:element name="donderdag">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vertoning" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dinsdag">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vertoning" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== StylishFlash/DatabankenExamenNieuw/Bioscoop/src/Middleware/Programmatie/Week1.xml
<?xml version="1.0" encoding="UTF-8"?>
<week xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Week.xsd">
	<maandag>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
	</maandag>
	<dinsdag>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
	</dinsdag>
	<woensdag>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
	</woensdag>
	<donderdag>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
	</donderdag>
	<vrijdag>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
	</vrijdag>
	<zaterdag>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
	</zaterdag>
	<zondag>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
		<vertoning>
			<id/>
			<is3D/>
			<taal/>
			<tijdstip type="date"/>
			<zetelreservatie/>
			<filmId/>
			<zaalId/>
		</vertoning>
	</zondag>
</week>
